package main

import (
	"io/ioutil"
	"log"
	"os"
	"path"
	"regexp"
	"strings"
)

var (
	conf = make(map[string]string)
)

const (
	fileName = "settings.ini"
	content  = `; Generated by https://github.com/RitterHou/time-alert
; 10/20/30/60/..., alert will be touched off if current_minute % this_number == 0
alert_time_point=30
; disable alert on this hours
; disabled_hours=22,23

; Please restart application after changing settings.
`
)

func init() {
	confFile := path.Join(rootDir, fileName)
	if _, err := os.Stat(confFile); os.IsNotExist(err) {
		writeFile(confFile, strings.Replace(content, "\n", "\r\n", -1))
	}
	confContent := readFile(confFile)

	var re = regexp.MustCompile("(;[\\d\\D]*?\n)") // 移除注释内容
	confContent = re.ReplaceAllString(confContent, "")

	confContent = strings.Replace(confContent, "\r", "\n", -1)
	for _, line := range strings.Split(confContent, "\n") {
		if strings.Contains(line, "=") {
			value := strings.Split(line, "=")
			conf[value[0]] = value[1]
		}
	}
}

func getConf() map[string]string {
	return conf
}

func readFile(filePath string) string {
	data, err := ioutil.ReadFile(filePath)
	if err != nil {
		log.Fatalln(err)
	}
	return string(data)
}

func writeFile(filePath string, data string) {
	err := ioutil.WriteFile(filePath, []byte(data), 0644)
	if err != nil {
		log.Fatalln(err)
	}
}
